# Parameters for the airplane

SOLVER:
  gpu: 0,
  max_iter: 960000
  test_iter: 200
  test_every_iter: 9600
  run: train
  lr_type: 'plateau'

train:
     dtype: points
     depth: 7
     distort: False
     axis: y
     shuffle: True
     take: -1
     batch_size: 2
     mask_ratio: 0.0
     return_pts: True
     use_majority: False
     location: "/mnt/nfs/work1/kalo/maverkiou/maria/withcolor"
     file_list: "/mnt/nfs/work1/kalo/maverkiou/maria/splits/train_split.txt"
     label_location: "/mnt/nfs/work1/kalo/maverkiou/maria/point_labels_32"

test:
     dtype: points
     distort: False  # no data augmentation
     depth: 7
     axis: y
     shuffle: True
     batch_size: 1
     return_pts: True
     location: "/mnt/nfs/work1/kalo/maverkiou/maria/withcolor"
     file_list: "/mnt/nfs/work1/kalo/maverkiou/maria/splits/val_split.txt"
     label_location: "/mnt/nfs/work1/kalo/maverkiou/maria/point_labels_32"


MODEL:
   name: hrnet
   nout: 31
   factor: 2
   signal_abs: True
   depth: 7
   depth_out: 7
 
LOSS:
   num_class: 31
   momentum: 0.9
   weight_decay: 0.0005
   point_wise: True

